package xin.xingk.www;

import cn.hutool.extra.qrcode.QrCodeUtil;
import cn.hutool.json.JSONObject;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import lombok.Data;
import xin.xingk.www.util.OkHttpUtil;

import javax.swing.*;
import java.awt.*;

/**
 * @Author: 陈靖杰
 * @Date: 2022/2/10 18:07
 * @Description:
 */
@Data
public class Qcode {
    private JPanel code;
    private JLabel jlebel;
    //二维码
    private ImageIcon qrCodeImg;
    //CK码
    private String ck;
    //时间戳
    private String t;

    private static Qcode qcode;

    public static Qcode getInstance() {
        if (qcode == null) {
            qcode = new Qcode();
        }
        return qcode;
    }

    public void init() {
        qcode = getInstance();
        try {
            JSONObject qrCodeUrl = OkHttpUtil.getQrCodeUrl();
            //二维码地址
            String codeContent = qrCodeUrl.getJSONObject("content").getJSONObject("data").getStr("codeContent");
            ck = qrCodeUrl.getJSONObject("content").getJSONObject("data").getStr("ck");
            t = qrCodeUrl.getJSONObject("content").getJSONObject("data").getStr("t");
            byte[] qrCode = QrCodeUtil.generatePng(codeContent, 180, 180);
            qrCodeImg=new ImageIcon(qrCode);
            qcode.getJlebel().setIcon(qrCodeImg);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString(), "获取二维码错误", JOptionPane.ERROR_MESSAGE);
        }
//        qcode.getJlebel().setText("123");
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        code = new JPanel();
        code.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        jlebel = new JLabel();
        jlebel.setText("Label");
        code.add(jlebel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return code;
    }

}
